<?php

use function Livewire\Volt\{title};

title('BueExports - Übersicht');

?>

<x-intranet-app-bue-exports::bue-exports-layout heading="BueExports App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-bue-exports::bue-exports-layout>